"""empty message

Revision ID: ed703be3ce10
Revises: a279c9131455
Create Date: 2020-03-04 14:42:25.324556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed703be3ce10'
down_revision = 'a279c9131455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('test_result', sa.Column('result', sa.String(length=20000), nullable=True))
    op.create_index(op.f('ix_test_result_name'), 'test_result', ['name'], unique=False)
    op.drop_index('ix_test_result_first_name', table_name='test_result')
    op.drop_index('ix_test_result_last_name', table_name='test_result')
    op.drop_column('test_result', 'first_name')
    op.drop_column('test_result', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('test_result', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_test_result_last_name', 'test_result', ['last_name'], unique=False)
    op.create_index('ix_test_result_first_name', 'test_result', ['first_name'], unique=False)
    op.drop_index(op.f('ix_test_result_name'), table_name='test_result')
    op.drop_column('test_result', 'result')
    op.drop_column('test_result', 'name')
    # ### end Alembic commands ###
